version: '3.8'

services:
  app:
    build: .
    ports:
      - "8096:8096"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Bing@1234
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8096/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      timeout: 10s

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bing@1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./local-db-data:/var/lib/postgresql/data
      - ./dump-postgres-202412110612.sql:/docker-entrypoint-initdb.d/dump-postgres-202412110612.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 10
      timeout: 10s

networks:
  app-network:
    driver: bridge